version: '3'

services:
  # PostgreSQL
  postgres:
    image: postgres:latest
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - mynetwork

  # Redis
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - mynetwork

  # Django
  web:
    image: savik1992/social_media:latest
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    networks:
      - mynetwork
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

networks:
  mynetwork:
    driver: bridge
