# Generated by Django 4.2.7 on 2023-11-22 20:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("social", "0002_post_likes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="followers",
        ),
        migrations.AlterField(
            model_name="profile",
            name="following",
            field=models.ManyToManyField(related_name="followers", to="social.profile"),
        ),
    ]
