# Generated by Django 4.2.7 on 2023-11-22 20:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("social", "0003_remove_profile_followers_alter_profile_following"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="bio",
            field=models.TextField(blank=True, default=""),
        ),
    ]
