# Generated by Django 4.2.7 on 2023-11-27 13:05

from django.db import migrations, models
import social.models


class Migration(migrations.Migration):
    dependencies = [
        ("social", "0004_alter_post_comments_alter_post_likes"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=social.models.social_image_file_path
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=social.models.social_image_file_path
            ),
        ),
    ]
