# Generated by Django 4.2.7 on 2023-11-27 15:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("social", "0006_alter_profile_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="following",
            field=models.ManyToManyField(
                blank=True,
                related_name="profile_followers",
                to="social.profile"
            ),
        ),
    ]
