# Generated by Django 4.2.7 on 2023-11-22 22:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("social", "0006_alter_profile_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="followers",
            field=models.ManyToManyField(
                related_name="my_following", to="social.profile"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="following",
            field=models.ManyToManyField(
                related_name="my_followers", to="social.profile"
            ),
        ),
    ]
