# Generated by Django 4.2.7 on 2023-11-22 23:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("social", "0009_alter_profile_followers_alter_profile_following"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="followers",
        ),
    ]
